### ISSUE TITLE
Possible inconsistency in ex_get_partial_conn

### ISSUE THREAD

**Issue by raovgarimella** [sandialabs/seacas#139]
The ex_get_partial_conn routine seems to have different meaning for its arguments depending on whether you are reading standard elements or NSIDED elements. For standard elements, the ```start_num``` indicates element ID and ```num_ent``` indicates number of elements for which to return the connectivity. On the other hand, it appears that for NSIDED elements, ```start_num``` indicates the offset (+1) at which the first node of the starting element occurs and ```num_ent``` indicates the number of nodes to read. I am attaching a small piece of code and 3 element mesh file that verifies this. Can you clarify please?

[partial_conn_test.tar.gz](https://github.com/gsjaardema/seacas/files/2913482/partial_conn_test.tar.gz)

**Comment by raovgarimella** [comment]
Also, is it true for NFACED type blocks and EX_FACE_BLOCK?

**Comment by gsjaardema** [comment]
I will try to take a look today.  There shouldn’t be different
behavior for the different block types or element types, so this is
probably a bug.  If you have a fix coded, you can submit as a PR to
github; otherwise I will try to fix soon.

There is an issue with the NFACED elements in parallel that I have
been meaning to address and which would require reimplementing how
they are stored and probably also the API; I’m not sure when I will
get to that.

..Greg

**Comment by raovgarimella** [comment]
Greg, Thank you. Sadly I don't have a fix for it.

**Comment by gsjaardema** [comment]
I think the issue is that `ex_get_partial_conn` does not know how to handle the polyhedral elements. This is related to my comment above about refactoring to support parallel with the NSIDED and NFACED elements.

The CGNS library had a similar issue and they have implemented a new internal storage which works for parallel and would also allow the `ex_get_partial_conn` to work correctly.  There are details at https://cgns.github.io/ProposedExtensions/NGON-CPEX-0041-v0.16.pdf

Basically, instead of storing the count of `faces per element` as I currently do, I need an index into the connectivity array giving the start index for element `i`.  The index array would be `element count + 1` in length and the number of faces for element `i` is `index[i+1] - index[i]` 

Currently, to get the correct index for element `i`, the library would need to sum the `faces per element` count from `1..i` which is doable, but not as efficient as it could be.  Exodus is a little better off than CGNS was since CGNS had count interspersed with ids, so had to read complete connectivity array to get an elements index and by then you had already read the bulk data so a partial capability cost more than reading everything on each processor.

I can probably fix the partial_conn function with current internal structure... Will take a look and see how difficult or if better to just bite the bullet and refactor internal storage...

Should probably add error/warning code that says the function doesn't work correctly for NSIDED and NFACED elements.

**Comment by raovgarimella** [comment]
Yes, that's right - you have to do the partial sum to know where to start retrieving the data. For now I am working around the problem by doing the partial sum outside for polygonal/polyhedral elements with extensive comments the behavior of ex_get_partial_conn is different for standard and polygonal elements. Thanks for confirming it.

By the way, the partial connectivity retrieval is awesome. I am using it to do more efficient parallel reads after doing a quick graph partitioning on rank 0. It was a bear to get the bookkeeping straight but I think I have it working.
