### ISSUE TITLE
Hardcoded USE_STD_SORT 

### ISSUE THREAD

**Issue by spyridon97** [sandialabs/seacas#365]
USE_STD_SORT seems to be a hardcoded define inside [packages/seacas/applications/epu/epu.C](https://github.com/sandialabs/seacas/blob/50bab220e45fc4f8030e6eaccc72f31dfdc03ebd/packages/seacas/applications/epu/epu.C)

Would it be possible to either make is a CMAKE Flag or remove it's usage?

In VTK in which we don't use the  [packages/seacas/applications/epu/epu.C](https://github.com/sandialabs/seacas/blob/50bab220e45fc4f8030e6eaccc72f31dfdc03ebd/packages/seacas/applications/epu/epu.C) file, we only use the ioss library, we have compilation failures when extra warnings are enabled, since USE_STD_SORT is not defined.  https://gitlab.kitware.com/vtk/vtk/-/issues/18798

**Comment by gdsjaar** [comment]
I will clean up the Ioss_Sort.h file.  Looks to have a lot of commented out junk in it.  I will also rename or remove the USE_STD_SORT to avoid confusion as it isn’t related to the symbol in epu.C
..Greg

From: Spiros Tsalikis ***@***.***>
Reply-To: sandialabs/seacas ***@***.***>
Date: Thursday, February 2, 2023 at 2:59 PM
To: sandialabs/seacas ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [sandialabs/seacas] Hardcoded USE_STD_SORT (Issue #365)


USE_STD_SORT seems to be a hardcoded define inside packages/seacas/applications/epu/epu.C<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsandialabs%2Fseacas%2Fblob%2F50bab220e45fc4f8030e6eaccc72f31dfdc03ebd%2Fpackages%2Fseacas%2Fapplications%2Fepu%2Fepu.C&data=05%7C01%7Cgdsjaar%40sandia.gov%7C798675e6654c47e8fd6e08db0568c6d7%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638109719788987678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jvrIzZcSzVdUnMXQGE8uyc38rBj%2BqEtIPqO6OmaQW%2BI%3D&reserved=0>

Would it be possible to either make is a CMAKE Flag or remove it's usage?

In VTK in which we don't use the packages/seacas/applications/epu/epu.C<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsandialabs%2Fseacas%2Fblob%2F50bab220e45fc4f8030e6eaccc72f31dfdc03ebd%2Fpackages%2Fseacas%2Fapplications%2Fepu%2Fepu.C&data=05%7C01%7Cgdsjaar%40sandia.gov%7C798675e6654c47e8fd6e08db0568c6d7%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638109719788987678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jvrIzZcSzVdUnMXQGE8uyc38rBj%2BqEtIPqO6OmaQW%2BI%3D&reserved=0> file, we only use the ioss library, we have compilation failures when extra warnings are enabled, since USE_STD_SORT is not defined. https://gitlab.kitware.com/vtk/vtk/-/issues/18798<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgitlab.kitware.com%2Fvtk%2Fvtk%2F-%2Fissues%2F18798&data=05%7C01%7Cgdsjaar%40sandia.gov%7C798675e6654c47e8fd6e08db0568c6d7%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638109719788987678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LJF6paQPvRzqU9cmveYHb9km39DKglZUrFDaINCBwiI%3D&reserved=0>

**Comment by spyridon97** [comment]
Thanks a lot! Let me know when the fix is on master

**Comment by gsjaardema** [comment]
Change was commited as dc19f8804c8edffedf3bf8a47d85c720ccaaea0b.  It still has the test on a define value, but uses `if defined` instead of `if`.  The macro isn't controllable except by editting the file itself, but for now I would prefer keeping it that way as just an emergency backup (although not that hard to add manually if it wern't there).

**Comment by gsjaardema** [comment]
I think the primary cause for this issue has been addressed.
